name = "wk"
main = "_worker.js"
compatibility_date = "2024-04-28"
usage_model = "bundled"
workers_dev = false

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "kv"
id = "ccf66d363820442c9c49bbf5a311d636"
